### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by josephdelon** [DrasilRNA/test#50]

**Comment by jilldevont** [comment]
?od ot evah i od tahW .ni em tel t'now eh tub elpmet eht raen naroZ eht ot klat ot em sllet nwoT eltsaC eluryH ni rellet enutrof eht dna evah I hciw romrA naroZ eht deen i em sllet andiM

**Comment by jilldevont** [comment]
elihw a rof ysub em peek lliw taht emag a tnaw I

**Comment by jevoneorwells** [comment]
I cant find 2 of them and im missing the one in the fog, can someone tell me how to get to it.

**Comment by jevoneorwells** [comment]
emiT fo elpmeT retne ot em gniwolla suht drows retsam htiw enots ekirts ot em wolla ton lliw emaG

**Comment by jevoneorwells** [comment]
Where are all the fairy fountains located?

**Comment by jevoneorwells** [comment]
.gnissarrabme tahwemos dna gnitartsurf yrev si siht ,pleh esaelP .gnihtyna gnihcuot ton dna ,B + nwod neht dna dnoces eno gnitiaw ,yawa thgir ti kooh ot B + nwod gnisu yb sexelfer namuhrepus gnivah deirt evah I ?od I od tahw dna ,taht yb naem ehs seod lleh eht tahW
."ti kooh uoy erofeb emit erom riah a tsuj ti gnivig yrt" ,yawa teg ti tel I emit elgnis yreve em gnillet aneH htiw ,ykcirt dna gniyonna s'ti taht si melborp ylno ehT
.erul gniknis eht teg yllanif nac I os txen ssab eluryh eht teg ot tnaw I ,ekip nailyh eht teg I erofeb tub ,knat hsif reh ot dda ot hsiftac nodro na tog I .ti tuoba enilno erehwyna ofni deliated on ot elttil s'ereht tub ,siht gniksa eb ot evah t'ndluohs I

**Comment by jevoneorwells** [comment]
I was wondering if the Miiverse Stamps are in entirely new chests or replace chests that were full of Rupees from the original.

**Comment by johnasduval** [comment]
I have multiple questions1.I found the girl in a cage that i tore open i think....then her boy friend in a room, i knocked him down off the pillar....then the third monkey which i unlocked, then i found the fourth monkey in a room with tiles, and monsters that pop up under the tiles....now....there is a chest behind the stairs....how do i get that!?2. I found occoo or what ever its name is....where is occoo jr?3.how do you get the boomerang!?4.In the main room how do you get the treasure chest hanging from th celing? and why does the third monkey (The one with a little tatoo on his arm) stand ontop of one of the pillars!?5. DOES ANYONE HAVE ANY USEFUL TIPS AND TRICKS TO GET ANYTHING IN THE GAME!?thanks!

**Comment by jevoneorwells** [comment]
???senim norog eht ni retal dleihs eht sI

**Comment by jephrynorman** [comment]
!!pleh ESAELP ...tops emas eht ot kcab mih teg ot deen yletarapsed I .nos ym fo ebucemaG no adleZ fo emag devas eht gnsare yb ssem a edam I

**Comment by jevoneorwells** [comment]
?em llet esaelp taht retfa od i od tahw tub tac eht teg ot woh wonk i ti teg i nehw dna dor gnihsif eht deen i won dna taht lla dna ssarg eht htiw gnos eht did tsuj i emag eht nI

**Comment by jennywaiver** [comment]
I pulled all the ropes in the rom to make the stairs spin. i see a chest and i think i need to get it. how do i get the chest? or if i dont need the chest how do i get through?

**Comment by jephrynorman** [comment]
So, I was playing Twilight Princess, and reached Lanayru's Province, in normal playthrough, you would descend the waterfall, and fall asleep until you reach Lake Hylia, I did that, but I had to leave and do something else, after that, instead of sleeping and waking up in front of the cavern, I just hit a wall. Thank you in advance.

**Comment by johnasduval** [comment]
?emag ym tratser ot evah I lliw dna hctilg ro eussi na ti si ro ateY dna oteY yb detceffa si ti fi wonk enoyna seoD .gniraeppa ton s'ti si melborp ylno eht tub ,gnidnats era ateY dna oteY erehw si eno tsal ehT .sluos eoP 5/4 tog I

**Comment by jennywaiver** [comment]
I can't seem to get this one particular tear inside Zora's River. I warm back to where the spirits are, her domain, and it shows on the little map there is a bug somewhere near a waterfall on the right hand side, but I just cannot seem to find it. I have gotten all of the others prior to this one, but I cannot seem to get this one for the life of me, any help?

**Comment by jennywaiver** [comment]
The 'worm creatures' I'm talking about are the creepy things that live under a tile, like in the Faron Woods and the City of the Sky. Please help me!!!

**Comment by jevoneorwells** [comment]
.pleh deen I .neercs ym no sraeppa reven "!NO HSIF" ,od I tahw rettam on ,llup ym emit I llew woh rettam on ,tiaw I gnol woh rettam on ,si melborp ehT .emoh nur dna em morf ti laets nac tac eht os hsif eht teg ot gniyrt m'I dna ,tey eavral eeb teg t'nac I ,oN .etib ot esufer yletulosba tsuj hsif eht tub ,ti esu ot gniyrt m'I .dor gnihsif eht tog tsuj I dna ,yrots eht fo gninnigeb eht raen m'I

**Comment by jevoneorwells** [comment]
???si ti erehw aedi on evah i dna rebmahc rorrim eht ot kcab og ot desoppus mi won tub ,rorrim eht fo seceip lla detcelloc won evaH

**Comment by jephrynorman** [comment]
?i em pleh enoemos nac t'nac tub )thgir taht delleps i fi wonk t'nod( treseD odureG eht taeb ot gniyrt neeb ev'I

**Comment by jevoneorwells** [comment]
So I bought a copy of twilight princess from a smaller game store called video game headquarters, game runs fine and works how it s supposed to. But after I turned into wolf link there has been a blue cursor on the map along with the players normal yellow. It doesn t move or anything, it s just there making me want to think that co-op was originally planned for the game.

**Comment by jennywaiver** [comment]
I can't get through it, and the wagon horse keeps running in rounds. It is kinda hard to Z lock the birds (with the gale boomerang), and those goblins only keep following.Is there a certain amount of time that need to pass before getting through? Or are there any good tactics to kill the monsters?

**Comment by zackeryhanice** [comment]
I'm in the temple in a round room behind the 3rd door from the original entrance you know the one with the big pillar in the middle with the stair case that moves. Well I don't know how to get past the water mills behind those two doors that don't have a key and I don't know where the key is to the doors with a lock and I don't know how to get to the chest on the pillar, the door, or the archway with a big rock blocking it.

**Comment by zackeryhanice** [comment]
sbmob 001 sdloh gab bmob tnaig ehT

**Comment by jevoneorwells** [comment]
?no nrut ot retaw eht teg i od woH

**Comment by johnasduval** [comment]
.otey ekil gnihton si ehs esuac yaw taht smees atros tI ?namuh a ehs sI

**Comment by johnasduval** [comment]
emiT fo elpmeT retne ot em gniwolla suht drows retsam htiw enots ekirts ot em wolla ton lliw emaG

**Comment by jennywaiver** [comment]
?od i od tahw ..daeha pu tsuj si ssob eht dna won yek gib eht hcaer ot yaw on sereht dna sseug i kcab ti nips t'nac uoY .syaw rehto owt eht fo desolc ti dna ti nups i dna tey yek gib eht nettog tndah i togrof i dna ...roolf eht no gniht rennips eht htiw moor gib eht ot tog i tub saw i erehw ot kcab og ot gniog saw I os ,gninnigeb eht ta uoy strats ti dna pu ti detrats i retal ,tiuq neht dna ,rennips eht deveicer I

**Comment by zackeryhanice** [comment]
I kno ur supposed to get a 4th bottle from Jovani when u get 20 poe souls. When I went there, he just filled my empty bottle with Great fairy tears. So how do I get the 4th bottle?

**Comment by johnasduval** [comment]
.nwot eht revo gnihctaw si yob eht erehw pohS bmoB eht fo foor eht morf tsehc eht ees nac uoY

**Comment by jevoneorwells** [comment]
Does anyone know if you have to press and hold the a button or press it repeatedly?

**Comment by jennywaiver** [comment]
): !tuo siht erugif em pleh nac ohw enoyna ot lufetarg m'I ,emitnaem eht nI .rewsna eht ssorca elbmuts ll'I ebyam os won noisrev DH eht hguorht gniyalp m'I .lanigiro eht deyalp ev'I ecnis elihwa neeb s'ti ecnis nettogrof ro gnihtemos dessim ev'I ebyaM ?thgir smrof egnahc osla dluow ehs kniht dluow uoy esuaceb em sesufnoc hcihw ,namuh sniamer adleZ ,revewoH .ecrofirT eht fo trap sah eh esuaceb )flow a( tsaeb enivid a otni snrut eh mlaer thgiliwT eht sretne kniL nehW .ecrofirT eht fo trap a sdleiw taht seno nesohc eht fo eno si adleZ taht dnatsrednu I

**Comment by jephrynorman** [comment]
.ti esu ot woh ro si ti tahw wonk ton od tub ,emag rats eht niw ot tohswalc eht deen I

**Comment by zackeryhanice** [comment]
?ykS eht ni ytiC fo gninnigeb eht morf korogrA ot kcab teg ylkciuq ot woh em llet esaelp enoemos naC).ton epoh I tsael ta--niaga revo lla gnihtyreve od ot evah t'nod I os evas did I( elpmet ykS eht ni ytiC eht fo gninnigeb eht morf trats ot evah I won dna ,no korogrA ekat dluoc I erofeb thgin tsal peelsa llef I ,iH

**Comment by jevoneorwells** [comment]
Hello!So I have collected all of the tears, tried to climb up to death mountain (only to be rolled over), talked to the shamon and tamed Epona. Now when I try to go back to Faron woods the path is blocked by a bunch of boulders! I have no idea why, and I can't get back to the woods! HELP!

**Comment by jevoneorwells** [comment]
ffo ym gnikcon speek eh dna snorog eht ta mi esuaceB

**Comment by jevoneorwells** [comment]
I can't beat Roll Goal for the frog bait so I need someone to tell me how to cacth it without it. I have looked at the Fishing Faq but it didn't help much.

**Comment by jennywaiver** [comment]
I got the 1st rod and went over to the fish.I pressed the minus button and the items screen did not pop up!HELP!!!!

**Comment by jephrynorman** [comment]
Question says it.after zants palace can i keep the upgraded master sword?

**Comment by jevoneorwells** [comment]
I have horse back, and need to go learn the new skill in Ordon Village to beat the Goron on top of the mountian but I cant get past the rocks that are blocking the way what do I do?

**Comment by jennywaiver** [comment]
!!!ti hcaer ot woh wonk tnod i tub hctiws eht si sirood eht evoba gniht der tnaig eht taht wonk I

**Comment by jennywaiver** [comment]
.slaedrO fO evaC eht taeb osla ev'I

**Comment by johnasduval** [comment]
gniliec morf nwod gnah taht snmuloc dnuor eht no rehtona ot tegrat eno morf evom t'nac dna yticykS ni m'I

**Comment by jevoneorwells** [comment]
I got him a bunch of times but keep dying than I respawn but I m out of arrows to shoot him with! Help!

**Comment by johnasduval** [comment]
?ereht kcab teg I od woH .tropelet dna lliw ta flow a otni mrofsnart ot ytiliba eht evah t'nod I .tuo era segdirb eht ro dekcolb rehtie era ereht dael taht syaw eht lla tub egalliV okirakaK ot kcab og ot tnaw I dna uryanaL tirips eht rof sraeT eht gnitteg dehsinif I

**Comment by johnasduval** [comment]
eht morf tohswalC elbuoD eht tog tsuj I

**Comment by jennywaiver** [comment]
?emag a fo daetsni retsaoc revlis ytterp a htiw pu dne I erofeb ,saedi ynA .norog tsrif eht tsuj si siht dna ,won semit 7 naht ssel on ngis revo emag eht nees evah I .htaed ym ot llaf I llit detpmorp ma I emit yreve A sserp I dna ,stoob nori eht evah I

**Comment by jevoneorwells** [comment]
I need help! I can't do the spin attack in the sword tutorial, my Nunchunk is not original, but it works just fine in Madworld and Donkey kong Barrel blast. I tried every single way to shake the nunchunk, but it is impossible to do the attack. Maybe my nunchunk is bronken and works only with up and down movements, I don't know... But if I can't solve this, I need to know: Can I beat this game without ever using the Spin Attack??? Cuz I really want to play it!

**Comment by jevoneorwells** [comment]
Are there still fire and ice arrows or did they get rid of them completely?

**Comment by johnasduval** [comment]
I'm at the Twilit Bloat fight in the HD version (also on hero mode if that matters). Simply put, I cannot grab the enemy to attack it, no matter what. I just keep bouncing off of it. I lunge straight for it after it swoops down and the electricity disappears, and it just WILL not register as me attacking it.

I was able to hit it within my first two attempts of the fight, but I haven't been able to replicate it. I even reset my console. I've seen no word of this online, apparently I'm the first to EVER report this issue online. Please give me some sort of help or guidance, because it's frustrating for something to just NOT work for no reason.

**Comment by johnasduval** [comment]
.noitanod a rof enim fo tsal eht desu tsuj i ruomrA cigaM eht teg ot deen I

**Comment by jevoneorwells** [comment]
erehwyreve dekooL

**Comment by johnasduval** [comment]
All the bridges are broken and I can't find hotspring water to give to the goron.

**Comment by johnasduval** [comment]
?!!pleh enoemos esaelP.kcuts ma I ,trap taht morf tub ,nwot eltsac eht ni "rotcod lacidem" eht rof eciovni eht nwohs evah I

**Comment by johnasduval** [comment]
.mih dnif t'nac I

**Comment by jephrynorman** [comment]
Ive tried everythind i can I went to gamewinners and cheatplanet and the said yo go as far east as I could and go bobber fishing. Ive been doing that for ours. plz help!

**Comment by johnasduval** [comment]
After I have returned Ilia's memory, she speaks someone Rod of the skies lady?who is this lady? Where I can find her?

**Comment by jephrynorman** [comment]
nwot eltsaC ni eltsac eht fo tnorf ni m'I

**Comment by jennywaiver** [comment]
How do I get the cradle from the monkey? I sent the hawk off the grassy tower next to Jaggle, it doesn't reach the monkey. I have not been able to play games for a ten years because of my wife's illness. I just opened this game I bought years ago. I want to get on my way. I am not even sure why I have to get the cradle.  Thanks in advance for your help.

**Comment by jephrynorman** [comment]
.mih ot teg ot woh wonk t'nod I

**Comment by jennywaiver** [comment]
I mean he said email him and hell tell u i did......that was a yer ago can someone help ma plz?

**Comment by johnasduval** [comment]
I'm in the temple and I'm on the second floor I release water for the first time there so what do I do now

**Comment by jephrynorman** [comment]
I have successfully defeated Ganondorf and seen the ending and credits,but once the credits have finished, it doesn't let me save the game so I have to defeat him again. Does anyone know how to fix this?
P.S.I play this game on the Nintendo Wii

**Comment by jennywaiver** [comment]
I'm at Death mountain inside their "mine" and there is a wall and Minda said you have to time it with the flame pillars... HELP!!!

**Comment by johnasduval** [comment]
Is she a human? It sorta seems that way cause she is nothing like yeto.

**Comment by jevoneorwells** [comment]
?ESAELP PLEH!!ssob tsal eht ot teg uoy od woh osla dna meht ot teg ot woh wonk tnod i tub elpmet tserof ni syeknom lla tog i

**Comment by jevoneorwells** [comment]
I ve played this game for years, and I m still not sure what bait is supposed to do. Does it cause your hook to attract fish more easily, or does it attract bigger fish? Does it give you more time to hook one once it s started nibbling?

I also read once that using the coral earring that Ralis gives you has the same effect as having bait on your line, but I m not sure if that s true at all.

**Comment by jephrynorman** [comment]
?yawa steg sseug i hsif eht ekil dna pu etomer eht krej dna yrt i tahw naht tub reve tahw ro hsif a sereht yas ot semit fo hcnub a ti teg i !hsif a hctac t'nac i dna yadot emag eht detrats tsuj i .siht ta kcus i ylsuoires ekiL

**Comment by johnasduval** [comment]
.pleh ruoy deen I .ni m?I noitautis emas eht ni yek rehtona gnitteg pu dne dna )em ekil( pu ssem yeht hcihw ni hguorhtklaw a nees t?nevah I dnA .KCUTS yletelpmoc m?I ,niahc dna llab evah t?nod ,sllabnonnac eht ot teg t?naC .kcuts m?I woN .rood gnorw eht no ti desU .yek a tog I dna ,sniuR kaepwonS ot tog tsuj I ,oS

**Comment by jephrynorman** [comment]
?gnissim m'I gnihtemos ereht sI .sedolpxe esuoh eht dna thgil fo sraet 3 rof flow a sa ni og uoY ?okirakaK ni esuoh eht pu wolB

**Comment by johnasduval** [comment]
I cant find the sinking lure for fishing i want to get it so i can catch a hylian loach

**Comment by jennywaiver** [comment]
.skrow lla siht woh em llet esaelp enoemos nac os ffuts yzarc siht lla dna rennips eht evah uoy litnu senim nerog eht otni teg tnac uoy neht dna ot woh nrael uoy erofeb praw nac uoy ti teg uoy ecno taht dias ti dna hctilg eht tuoba daer I

**Comment by johnasduval** [comment]
?evah uoy nac selttob ynam woh dna ,leef lluf eht gnitteg m'I erus eb ot latot evah nac I straeh ynam woh wonk ot tnaw tsuj I .stseuq elttil eht lla gnihsinif evol I emag eht fo ecnairepxe lluf eht teg ot gnitnaW

**Comment by jennywaiver** [comment]
So I entered twilight in the Lanayru province without getting dthe vessel of light and I am not able to go back and get it. I already completed Death mountain and I have no idea how to get vessel of light. I followed the scent of Ilia and I'm also not allowed to go to Hyrule Lake (I think that's what it's called). Please help me, thank you in advance!

**Comment by jennywaiver** [comment]
Just name the Zelda games in order ?

**Comment by johnasduval** [comment]
?eno iiw eht morf ]noisrev ncg eht[ desrever s'ti syas ti nehw naem ti stahw tub ,scihparg dna slortnoc eht taht tcaf eht sediseb wonk I

**Comment by johnasduval** [comment]
I recall being able to before, but I can't remember how now.Remember, the keyword here is BEFORE Malo takes over the shop. I know what I need to do to get magic armor.

**Comment by jennywaiver** [comment]
.pleh esaelp kcuts won ma i tuhs deniamer rood eht moor taht ni sretsnom owt eht dellik dna moor thgir eht ot tnew neht i tuhs dniamer rood eht dna tuo gniog tpek eno tub sehcrot eht lla til dna moor taht ni stab eht lla dellik dna tfel eht ot tnew i tsehc eht o pu tog dna no til eht tuo welb dna sehcrot owt til i dna moor erilednahc eht ni rood siht hguorht tog tsuj i kO

**Comment by jennywaiver** [comment]
?tsaf seepur 003 teg ot yawyna os egdirb eht rof seepur ym lla detanod i tib nonnac eht rof seepur 003 teg ot yaw kciuq a deen I

**Comment by johnasduval** [comment]
!!pleh ESAELP ...tops emas eht ot kcab mih teg ot deen yletarapsed I .nos ym fo ebucemaG no adleZ fo emag devas eht gnsare yb ssem a edam I

**Comment by johnasduval** [comment]
After she uses her power to save Midna she disappears and a force field appears over the castle. Why did that happen? I already beat the game several times but when I get to that part I don't get it. So what happened to her?

**Comment by johnasduval** [comment]
While following a game faq, the next main part I have to do is the underwater temple,I have to go to get the second and third bomb bag. There lies the problem. I'm human Link, and can't find ANY way to get back there. The cave shortcut in northern Hyrule is blocked by ice, so I have no idea how to get back to Zora's Domain. Is there anything special that I need to do to melt the ice? Please help. I have been trying to beat this game for quite some time.

**Comment by jennywaiver** [comment]
I saved the girl monkey and then i saved her friend I went threw all doors and saved another monkey but I dont know what to do after that...

**Comment by johnasduval** [comment]
).rennips htiw ot pmuj uoy taht niatnuof eht ni tsehc eht naem tnod i( ?tsehc eht ot teg i od woH .tsehc sah rehto eht dna tniop elpparg sah eno ,srewot 2 era ereht ,nwot eltsac fo htuoS

**Comment by johnasduval** [comment]
?kniL no egamad laminim htiw ,syug eseht htiw gnilaed ni ecivda emos evah I naC .)ssob tsal eht rof sraeT syriaF eht tog ylno dna neht dah I 4 fo tuo 3( selttob ym gniytpme ylraen ,sromra rieht fo %52 ffo gnippihc neve erofeb secam rieht htiw em degnab-gnag yeht dna ,eltsaC eht ni stunkraD suoenatlumis OWT thguof ydaerla evI taht si melborp ehT .slaedrO fo evaC eht od ot gnitnaw osla dna tseuq somrA cigaM eht gniod mI .emag eht hsinif ot esolc mI

**Comment by jennywaiver** [comment]
I can't find adoor to go throgh.I only found where the boss key is and can't get to it.

**Comment by johnasduval** [comment]
Could someone tell me the name of the music played when you select your save file?
